name: Controll PR labels using action comments

on:
  issue_comment:
    types: [created, edited]
  workflow_call:


jobs:
  skip-test-labeler:
    # This job adds skip test labels to PRs for allowed tests
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Skip check_pruned_graph test
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.comment.body, '/test skip check_pruned_graph') }}
      with:
        labels: tests/skips/check_pruned_graph

  trigger-pipeline:
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Trigger isv hosted pipeline
      if: ${{ startsWith(github.event.comment.body, '/pipeline restart operator-hosted-pipeline')  && contains( github.event.issue.labels.*.name, 'operator-hosted-pipeline/failed') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: pipeline/trigger-hosted
    - name: Trigger isv release pipeline
      if: ${{ startsWith(github.event.comment.body, '/pipeline restart operator-release-pipeline')  && contains( github.event.issue.labels.*.name, 'operator-release-pipeline/failed') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: pipeline/trigger-release
    - name: Trigger community hosted pipeline
      if: ${{ startsWith(github.event.comment.body, '/pipeline restart community-hosted-pipeline')  && contains( github.event.issue.labels.*.name, 'community-hosted-pipeline/failed') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: pipeline/trigger-hosted
    - name: Trigger community release pipeline
      if: ${{ startsWith(github.event.comment.body, '/pipeline restart community-release-pipeline')  && contains( github.event.issue.labels.*.name, 'community-release-pipeline/failed') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: pipeline/trigger-release
